apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ukv2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-ukv2@sha256:e69bcc6a0b2d5bb2e717bd02e034b4efedf846ca10a0bd79ba902634bf28bd9d
        name: my-nodejs
        resources: {}
status: {}
